updated pipeline running coverage with right trigger

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,9 +1,10 @@
-name: CI/CD
+name: CI Pipeline
 
 on:
   push:
     branches:
       - main
+  pull_request:
 
 jobs:
   test:
@@ -13,30 +14,22 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Node.js
+      - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: 18
+          node-version: '18'
 
       - name: Install dependencies
-        run: npm ci
+        run: npm install
 
-      # Esegui i test con coverage
       - name: Run tests with coverage
-        run: npx vitest --coverage
+        run: npm run coverage
 
-      # Debug della directory di coverage
-      - name: Debug coverage folder
-        run: |
-          echo "Listing coverage folder contents:"
-          ls -R ./coverage
-
-      # Salva i report di coverage come artefatto
-      - name: Save coverage report
+      - name: Upload coverage report
         uses: actions/upload-artifact@v3
         with:
           name: coverage-report
-          path: ./coverage/
+          path: coverage/
 
   check-coverage:
     runs-on: ubuntu-latest
@@ -51,6 +44,21 @@ jobs:
         with:
           name: coverage-report
 
+      - name: Install utilities
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y jq bc
+
+      - name: Check if coverage-summary.json exists
+        run: |
+          echo "Listing coverage files for verification:"
+          ls ./coverage
+          if [ ! -f ./coverage/coverage-summary.json ]; then
+            echo "Coverage report not found!"
+            exit 1
+          fi
+          echo "Coverage report found"
+
       - name: Check test coverage
         run: |
           COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
@@ -59,33 +67,3 @@ jobs:
             echo "Test coverage is below 90%, cannot proceed."
             exit 1
           fi
-
-  deploy:
-    runs-on: ubuntu-latest
-    needs: check-coverage
-    permissions:
-      contents: read
-      pages: write
-      id-token: write
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Install modules
-        run: npm ci
-
-      - name: Build dist
-        run: npm run build
-
-      - name: Setup pages
-        uses: actions/configure-pages@v3
-
-      - name: Upload dist folder
-        uses: actions/upload-pages-artifact@v1
-        with:
-          path: "./dist"
-
-      - name: Deploy to Github Pages
-        id: deployment
-        uses: actions/deploy-pages@v1
